### ISSUE TITLE
Backend TODO

### ISSUE THREAD

**Issue by hang333** [WizardL/Misato#11]
关于后台
- [x] FB登录功能
- [x] 帖子投诉需要 FB id, 不算登录
- [x] 后台管理帖子功能

关于贴文发布
- [x] Goo.gl 短网址功能
- [x] 通知用户 "贴文通过" 的消息
- [x] 发图功能
- [ ] 制图功能

关于贴文排序
- [x] 每日最热贴文
- [x] 全年度 Top 20 贴文
- [x] 最新贴文

后端问题
- [x] 关于ID的分配
# 

Backend
- [x] FB login functionality
- [x] FB ID is required for reporting
- [x] Managing post functionality

Posting
- [x] Goo.gl URL shortening functionality
- [x] Telling user that the post is posted successfully
- [x] Ability to upload photos
- [ ] Ability to create photos

Posts
- [x] Daily Hottest Posts
- [x] All-year Top 20 Posts
- [x] Latest Posts

Backend problems
- [x] ID assigning

**Comment by sooxiaotong** [comment]
FB 登入是指page 登入？还是用户登入？

**Comment by hang333** [comment]
用户登录，我想问你能在没用户授权的情况下取得page access token么?

**Comment by sooxiaotong** [comment]
不是我是说匿名帖文的时候，用户需要登入他自己的fb么？若要获得fb page token，管理员必须以page admin登入@。@

**Comment by hang333** [comment]
@sooxiaotong 如果用户要接收 "您的帖子已被通过" 的notification, 用户是需要登录的

**Comment by sooxiaotong** [comment]
你们要手动管理，苦了 。 。。不是匿名发布，让没有面子书的人也可以使用，所以才要做多一个abuse page啊啊啊啊啊

**Comment by hang333** [comment]
![image](https://cloud.githubusercontent.com/assets/3853064/16900625/8c2d51fa-4c5c-11e6-9e81-aa7b5bf01f2e.png)

**Comment by hang333** [comment]
是可以自行设置的

**Comment by sooxiaotong** [comment]
这个我看到啊，如果不做这个选择的话，可省很多功夫，就让读帖文的人自己看着办，让读者负责举报这一块

**Comment by hang333** [comment]
因为是给中学的，所以可能有很多无脑文..

**Comment by sooxiaotong** [comment]
那么你做吧，这块我。。。做不到

**Comment by zypeh** [comment]
我目前在做着每日贴文的前端部分。#12

**Comment by zypeh** [comment]
后台管理帖子需要一个界面啊，需要？
我们可以通过一个算法来判定这个是不是短时间很多人投诉，之后再来删除。手动的话就简单的页面表格删除帖子而已。没必要做到很复杂。

**Comment by hang333** [comment]
@zypeh yes
